baseURL = "https://cyclicboosting.org"
languageCode = "en-us"
title = "Cyclic Boosting"
theme = "timer-hugo"
# post pagination
paginate = "2" # see https://gohugo.io/extras/pagination/
googleAnalytics = "G-YXTCWS7BW3"


# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Navbar Menus
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Documentation"
url = "https://cyclic-boosting.readthedocs.io/en/latest/"
weight = 2

[[menu.main]]
name = "Example"
url = "https://github.com/Blue-Yonder-OSS/cyclic-boosting-example"
weight = 3

[[menu.main]]
name = "GitHub"
url = "https://github.com/Blue-Yonder-OSS/cyclic-boosting"
weight = 4



# Site Params
[params]
home = "Home"
logo = "images/Tiny_logo_50px.png"
dateFormat = "6 January 2006"
# Meta data
description = "The lightning-fast machine learning library that delivers exceptional results with minimal fine-tuning"
author = "Blue Yonder"
# Google Analitycs
#googleAnalitycsID = "G-YXTCWS7BW3"

# contact form action
contactFormAction = "#" # contact form works with https://formspree.io

# Banner Section
[params.banner]
enable = true
bgImage = "images/Sebastian_Neubauer_A_swirl_of_data_and_visualizations_3d_plots__d2938bed-18bd-4344-b9f4-0abc242fb011.png"
heading = "Cyclic Boosting"
description = "The lightning-fast machine learning library that delivers exceptional results with minimal fine-tuning"
# button
btn = true
btnText = "Getting Started"
btnURL = "https://cyclic-boosting.readthedocs.io/en/latest/install.html"

# flip text
[[params.banner.flipText]]
title = "FAST"
[[params.banner.flipText]]
title = "ROBUST"
[[params.banner.flipText]]
title = "ACCURATE"

# Homepage About Section
[params.about]
enable = true
title = "What is Cyclic Boosting"
content = "Cyclic Boosting is a Python library implementing the family of machine learning algorithms of the same name, which is described in <a href=\"https://arxiv.org/abs/2002.03425\" title=\"https://arxiv.org/abs/2002.03425\">Cyclic Boosting - an explainable supervised machine learning algorithm</a> and <a href=\"https://arxiv.org/abs/2009.07052\" title=\"https://arxiv.org/abs/2009.07052\">Demand Forecasting of Individual Probability Density Functions with Machine Learning</a>. It contains efficient, off-the-shelf, general-purpose supervised machine learning methods for both regression and classification tasks."
image = "images/Sebastian_Neubauer_very_simplistic_logo_of_a_spiral_final_transparent.png"

# Call to Action
[params.cta]
enable = true
title = "SO WHAT YOU THINK ?"
content = "We value your thoughts and feedback on our open-source project."
btnText = "Contribute on github"
btnURL = "https://github.com/Blue-Yonder-OSS/cyclic-boosting"

# Portfolio Section On Homepage
[params.portfolio]
enable = true
title = "Use Cases"
subtitle = "Cyclic Boosting can be used for many different use-cases, here are just some examples"

# social icon
[[params.socialIcon]]
icon = "ion-social-twitter"
url = "https://twitter.com/BlueYonderTech"

